### ISSUE TITLE
Equisat GRC crashes

### ISSUE THREAD

**Issue by N6RFM** [BrownSpaceEngineering/gr-equisat_decoder#1]
Hi Neighbors,

Unable to use equisat.grc.  Flowgraph crashes immediately after start.

Generating: '/home/bob/gr-equisat_decoder/apps/equisat.py'
Executing: /usr/bin/python2 -u /home/bob/gr-equisat_decoder/apps/equisat.py
Press Enter to quit: 
>>> Done
Is this complete or still a work in progress?  All dependencies seem to be met otherwise.  During install, YAML was also requested.  Appeared to satisfy bu installing python-yaml and python3-yaml using Synaptic.  OS is Linux Mint 18.3 Sylvia.  

Thanks,
Bob N6RFM
Bristol, RI

**Comment by N6RFM** [comment]
Follow-up.  Equisat flowgraph crashes despite disabling QT GUI timesink when in No Gui mode.  Seems to run OK when in QT mode despite QT GUI Timesink remaining disabled. In Options block, for No GUI mode, need to select "run to completion" as default mode.  Then runs OK on No Gui mode.  Otherwise, set QT Mode.

**Comment by MckennaCisler** [comment]
Hi Bob,

I found a few issues that could be causing this, and just [committed](https://github.com/BrownSpaceEngineering/gr-equisat_decoder/commit/f772295a5df08cb7f4d7af5cb432538c03091811) the fixes. 

The two things I think might've caused your crash were me omitting the `sudo ldconfig` command in the install instructions (it should be run at the end), and a hidden dependecy on gr-satellites that I removed.

I'm not sure why things worked in QT mode, but it's possible the problem was just hidden with the GUI thread running. Let me know if running `sudo ldconfig` and the new flowgraph don't work and I'll investigate further.

Thanks for your help in catching this!

**Comment by N6RFM** [comment]
Hi Mckenna,

Thanks for responding.  Not sure what is going on.  Happy to help further
as needs arise.

Just pulled the new commits, and reinstalled.  Also, sudo ldconfig (which I
generally do anyway to refresh the wheel).
Unfortunately, in no GUI mode same error.

Generating: '/home/bob/gr-equisat_decoder/apps/equisat.py'

Executing: /usr/bin/python2 -u /home/bob/gr-equisat_decoder/apps/equisat.py

Press Enter to quit:
>>> Done

Thanks,

Bob

**Comment by N6RFM** [comment]
Just noticed that in the "Options" block, "prompt for exit" was selected.  Changed to "Run to completion".  Now does not halt.  :-)  Will try for a few passes,  TKS.

**Comment by MckennaCisler** [comment]
Ah, that makes sense, just updated that. Thanks and good luck!
